export const Files = {
  CSS: "CSS",
  CSSColor: "CSSColor",
  HTML: "HTML",
  SVG: "SVG",
  React: "React",
  ReactComponent: "ReactComponent",
  ReactRouting: "ReactRouting",
  TypeScript: "TypeScript",
  JavaScript: "JavaScript",
  JavaScriptAsync: "JavaScriptAsync",
  window: "window",
  StyledCompo: "Packages\\StyledCompo",
  ReactFetchState: "Packages\\ReactFetchState",
  ReactHookForm: "Packages\\ReactHookForm",
  Storybook: "Packages\\Storybook",
  zustand: "Packages\\zustand",
}
